services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 17101
      POSTGRES_DB: fin-control
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fin-control-network

volumes:
  postgres_data:

networks:
  fin-control-network:
    driver: bridge
